version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "50"
